version: '3'

services:
  web-app:
    container_name: web-app
    image: blog-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "${BINDING_PATH}:/app"
    env_file:
      - .env
